export const COCKTAIL_RECIPE_STATIC_UTL = process.env.NEXT_PUBLIC_STATIC_URL;
export const COCKTAIL_RECIPE_API_URL = process.env.NEXT_PUBLIC_API_URL;
export const COCKTAIL_RECIPE_SERVER_API_URL = process.env.NEXT_PUBLIC_SERVER_API_URL;
